"""class parallel grade auto-increment

Revision ID: e170b7377a32
Revises: ec92a82d53db
Create Date: 2026-09-06 18:45:12.973194+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e170b7377a32'
down_revision: Union[str, Sequence[str], None] = 'ec92a82d53db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('letter', sa.String(length=4), nullable=True))
    op.add_column('classes', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.alter_column('classes', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('classes', 'graduation_year')
    op.drop_column('classes', 'letter')
    # ### end Alembic commands ###
