"""teacher-managed students, school login prefix

Revision ID: fb07902c12fe
Revises: e170b7377a32
Create Date: 2026-09-06 19:07:14.639944+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb07902c12fe'
down_revision: Union[str, Sequence[str], None] = 'e170b7377a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_invite_code'), table_name='classes')
    op.drop_column('classes', 'invite_code')
    # login_prefix: временный дефолт из id, чтобы не падать на существующих строках
    op.add_column('schools', sa.Column('login_prefix', sa.String(length=16), nullable=False,
                                       server_default=sa.text("left(md5(random()::text), 8)")))
    op.alter_column('schools', 'login_prefix', server_default=None)
    op.add_column('schools', sa.Column('student_seq', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('schools', 'student_seq', server_default=None)
    op.add_column('schools', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_schools_login_prefix'), 'schools', ['login_prefix'], unique=True)
    op.create_foreign_key('fk_schools_created_by', 'schools', 'users', ['created_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.drop_column('schools', 'verified')
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'username')
    op.add_column('schools', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_schools_created_by', 'schools', type_='foreignkey')
    op.drop_index(op.f('ix_schools_login_prefix'), table_name='schools')
    op.drop_column('schools', 'created_by')
    op.drop_column('schools', 'student_seq')
    op.drop_column('schools', 'login_prefix')
    op.add_column('classes', sa.Column('invite_code', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_classes_invite_code'), 'classes', ['invite_code'], unique=True)
    # ### end Alembic commands ###
